-- Insertar Idiomas
INSERT INTO IDIOMAS (NOMBRE_IDIOMA) VALUES ('Español'), ('Inglés');

-- Insertar Editoras
INSERT INTO EDITORAS (NOMBRE_EDITORA, DESCRIPCION) 
VALUES ('Alfaguara', 'Editorial literaria'), 
       ('Penguin Books', 'Editorial internacional');

-- Insertar Tipos de Bibliografía
INSERT INTO TIPOS_BIBLIOGRAFIAS (NOMBRE_BIBLIOGRAFIA, DESCRIPCION)
VALUES ('Novela', 'Narrativa de ficción'), 
       ('Ensayo', 'Texto argumentativo');

-- Insertar Autores
INSERT INTO AUTORES (NOMBRE_AUTOR, PAIS_ORIGEN, CODIGO_IDIOMA)
VALUES ('Gabriel García Márquez', 'Colombia', 1),
       ('George Orwell', 'Reino Unido', 2);


-- Insertar libro (Gabriel García Márquez - Alfaguara - Español)
INSERT INTO LIBROS (TITULO, SIGNATURA_TOPOGRAFICA, ISBN, CODIGO_EDITORA, ANIO_PUBLICACION, CIENCIA, CODIGO_IDIOMA)
VALUES ('Cien años de soledad', 'PQ8180.17.A73 C5', '9780307474728', 1, 1967, 'Literatura', 1);


-- Asociar libro con bibliografía (Novela)
INSERT INTO LIBROS_BIBLIOGRAFIAS (CODIGO_LIBRO, CODIGO_BIBLIOGRAFIA)
VALUES (1, 1);  -- 1 = primer libro, 1 = Novela

-- Asociar libro con autor (Gabriel García Márquez)
INSERT INTO LIBROS_AUTORES (CODIGO_LIBRO, CODIGO_AUTOR)
VALUES (1, 1);  -- 1 = primer libro, 1 = Gabriel García Márquez


SELECT 
    L.TITULO,
    L.ISBN,
    E.NOMBRE_EDITORA,
    I.NOMBRE_IDIOMA AS IDIOMA_LIBRO,
    A.NOMBRE_AUTOR,
    A.PAIS_ORIGEN,
    IB.NOMBRE_BIBLIOGRAFIA
FROM LIBROS L
INNER JOIN EDITORAS E ON L.CODIGO_EDITORA = E.CODIGO_EDITORA
INNER JOIN IDIOMAS I ON L.CODIGO_IDIOMA = I.CODIGO_IDIOMA
INNER JOIN LIBROS_AUTORES LA ON L.CODIGO_LIBRO = LA.CODIGO_LIBRO
INNER JOIN AUTORES A ON LA.CODIGO_AUTOR = A.CODIGO_AUTOR
INNER JOIN LIBROS_BIBLIOGRAFIAS LB ON L.CODIGO_LIBRO = LB.CODIGO_LIBRO
INNER JOIN TIPOS_BIBLIOGRAFIAS IB ON LB.CODIGO_BIBLIOGRAFIA = IB.CODIGO_BIBLIOGRAFIA
WHERE L.ELIMINADO IS NULL OR L.ELIMINADO = 0;


-- Insertar Tanda Laboral
INSERT INTO TANDA_LABOR (NOMBRE_TANDA, HORA_INICIO, HORA_FIN)
VALUES ('Mañana', '08:00', '14:00');

-- Insertar Empleado
INSERT INTO EMPLEADOS (NOMBRE, APELLIDO, CEDULA, CODIGO_TANDA, PORCENTAJE_COMISION, FECHA_INGRESO)
VALUES ('Juan', 'Pérez', '00112233445', 1, 10.0, '2023-01-15');

-- Insertar Usuario
INSERT INTO USUARIOS (NOMBRE, APELLIDO, CEDULA, NUMERO_CARNET, CODIGO_TIPO)
VALUES ('Ana', 'Martínez', '00998877665', 'A123456789', 1); -- 1 = Física


-- Insertar Préstamo (empleado 1, usuario 1, libro 1)
INSERT INTO PRESTAMO (
    CODIGO_EMPLEADO,
    CODIGO_LIBRO,
    CODIGO_USUARIO,
    FECHA_PRESTAMO,
    FECHA_DEVOLUCION,
    MONTO_DIA,
    CANTIDAD_DIAS,
    COMENTARIO
)
VALUES (
    1,  -- Empleado Juan Pérez
    1,  -- Libro "Cien años de soledad"
    1,  -- Usuario Ana Martínez
    '2025-06-20',
    '2025-06-25',
    2.50,
    5,
    'Lectura recomendada para clase de literatura'
);


SELECT 
    P.CODIGO_PRESTAMO,
    U.NOMBRE + ' ' + U.APELLIDO AS NOMBRE_USUARIO,
    E.NOMBRE + ' ' + E.APELLIDO AS NOMBRE_EMPLEADO,
    L.TITULO AS LIBRO,
    L.ISBN,
    T.NOMBRE_TANDA,
    P.FECHA_PRESTAMO,
    P.FECHA_DEVOLUCION,
    P.MONTO_DIA,
    P.CANTIDAD_DIAS,
    P.COMENTARIO
FROM PRESTAMO P
INNER JOIN USUARIOS U ON P.CODIGO_USUARIO = U.CODIGO_USUARIO
INNER JOIN EMPLEADOS E ON P.CODIGO_EMPLEADO = E.CODIGO_EMPLEADO
INNER JOIN TANDA_LABOR T ON E.CODIGO_TANDA = T.CODIGO_TANDA
INNER JOIN LIBROS L ON P.CODIGO_LIBRO = L.CODIGO_LIBRO
WHERE P.ELIMINADO IS NULL OR P.ELIMINADO = 0;
